### ISSUE TITLE
App crashes while trying to connect, happens only on ZenFone 4 (A450CG) Android 4.4.2

### ISSUE THREAD

**Issue by mussa-ibragimov** [centrifugal/centrifuge-mobile#13]
Caused by java.lang.UnsatisfiedLinkError
Native method not found: go.Seq.init:()V

```
go.Seq.init (Seq.java)
go.Seq.<clinit> (Seq.java:38)
```

**Comment by FZambia** [comment]
Hello @mussa-ibragimov 

This looks similar to https://github.com/golang/go/issues/19492 - can you provide full trace of crash to address this to gomobile repo?

**Comment by FZambia** [comment]
Closing since no response from OP and no steps to reproduce.
