### ISSUE TITLE
Subscription always null in PublishHandler

### ISSUE THREAD

**Issue by danilashamin** [centrifugal/centrifuge-mobile#16]
Hello. The problem is that when a new message arrives in the onPublish method, the Subscription variable is always null. What could be the problem?

subEvents.onPublish((p0, p1) -> /*some action*/);

**Comment by FZambia** [comment]
Hello @danilashamin 

Thanks for report, looks like I missed this while making proxy to `centrifuge-go` types. The solution is not simple in this case unfortunately. Looks like we need to change library API a bit to fix this, changes won't be dramatic but current API will be broken. I already have working prototype at my laptop - will try to figure out how it behaves.

**Comment by FZambia** [comment]
@danilashamin I've made several changes in libraries - please look, what do you think. If no objections appear I'll merge everything tomorrow and create new `0.2.0` tags here and in `centrifuge-go`

**Comment by FZambia** [comment]
Hmm, I have not removed it - could you show where you noticed this?

**Comment by FZambia** [comment]
All merged - please check it out

**Comment by danilashamin** [comment]
> Hmm, I have not removed it - could you show where you noticed this?
Sorry, I misunderstood the code. Just saw you comment it out.

**Comment by FZambia** [comment]
@danilashamin did you have a chance to check how it works for you? Can we close this issue?
