### ISSUE TITLE
Warning in iOS 

### ISSUE THREAD

**Issue by daukabase** [centrifugal/centrifuge-mobile#21]
<img width="898" alt="Screen Shot 2020-08-19 at 12 04 46" src="https://user-images.githubusercontent.com/31764630/90598119-3f73d300-e214-11ea-8f3f-a406dbde0775.png">

**Comment by FZambia** [comment]
Hello! Hmm... warning happens inside API which seems exported by mistake – `SubscriptionEventHub` is not useful in public scope, I suppose just removing that type from public entities will resolve this case.

**Comment by FZambia** [comment]
Published v0.5.3, check it out
