### ISSUE TITLE
history publication does not received after subscribing on channel

### ISSUE THREAD

**Issue by puryagh** [centrifugal/centrifuge-mobile#22]
hi dear

after a few days of working on centrifuge-java, finally i use centrifuge-mobile and it is very simple and fast

but i have a problem on channel history

on ios (swift) and  web when i subscribe on public channel that has below configuration 

`
    {
      "name": "public",
      "anonymous": true,
      "publish": true,
      "join_leave": true,
      "presence": false,
      "presence_stats": false,
      "history_size": 1,
      "history_lifetime": 3600
    }
` 

history publications receives correctly
but on android with with centrifuge-mobile library histories publications not receives

please help me to solve this

**Comment by FZambia** [comment]
Hello, please provide steps to reproduce (with version and code example).

**Comment by FZambia** [comment]
Closing since no response from OP and no steps to reproduce.
