### ISSUE TITLE
Final step: update mobile examples

### ISSUE THREAD

**Issue by FZambia** [centrifugal/centrifuge-mobile#4]
And then looks we are done

**Comment by TianDaGe** [comment]
How to receive messages? it seems, there is not receiveMessageHandler like ios native sample.
right?

**Comment by FZambia** [comment]
@TianDaGe here is an example for Go: https://github.com/centrifugal/centrifuge-mobile/blob/master/examples/go/example.go#L22 , for iOS: https://github.com/centrifugal/centrifuge-mobile/blob/master/examples/go/example.go#L22

**Comment by TianDaGe** [comment]
Hello @FZambia

I used config.json like this.
```
{
  "secret": "secret",
  "web": true,
  "admin_password": "password",
  "admin_secret": "secret",
  "publish": true,
  "presence": true,
  "join_leave": true,
  "watch": true,
  "namespaces": [
    {
      "name": "public",
      "anonymous": true,
      "publish": true,
      "watch": true,
      "presence": true,
      "join_leave": true,
      "history_size": 10,
      "history_lifetime": 30,
      "recover": true
    }  
  ]
}

```
Then i can receive message in localhost admin. but I can't get message in other side.(pc or mobile app)
what am i wrong?

**Comment by FZambia** [comment]
Sorry but I can't say what's wrong seeing just a Centrifugo config file, most probably your connection with Centrifugo was not successfully established for some reason - wrong token, wrong connection address maybe?

**Comment by TianDaGe** [comment]
pubish is working fine. Only subscribe is not working fine.
I will share objective-c code.
```

#import <Centrifuge/Centrifuge.h>

#import "ViewController.h"

@interface ViewController ()<CentrifugeConnectHandler, CentrifugeDisconnectHandler, CentrifugeMessageHandler>
{
    CentrifugeSub *sub;
}

@property (weak, nonatomic) IBOutlet UILabel *label;
@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    
    _label.text = @"Connecting...";
    
    CentrifugeCredentials *creds = CentrifugeNewCredentials(@"42", @"1488055494", @"", @"24d0aa4d7c679e45e151d268044723d07211c6a9465d0e35ee35303d13c5eeff");
    NSString *url = @"ws://192.168.1.109:9000/connection/websocket";
    
    CentrifugeClient *client = CentrifugeNew(url, creds, CentrifugeNewEventHandler(), CentrifugeDefaultConfig());
    NSError *error = nil;
    if (![client connect:&error]) {
        if (error != nil) {
            _label.text = @"Error on connect...";
        }
    }
    
    CentrifugeSubEventHandler *subEventHandler = CentrifugeNewSubEventHandler();
    [subEventHandler onMessage:self];
    
    error = nil;
    sub = [client subscribe:@"public:chat" events:subEventHandler error:&error];
    if (error != nil) {
        _label.text = @"Subscribe error";
    }
    
    NSString *data = @"{\"input\": \"hello\"}";
    error = nil;
    if (![sub publish:[data dataUsingEncoding:NSUTF8StringEncoding] error:&error]) {
        if (error != nil) {
            _label.text = @"Publish error";
        }
    }
}

- (void)onConnect:(CentrifugeClient *)p0 p1:(CentrifugeConnectContext *)p1 {
    _label.text = [NSString stringWithFormat:@"Connected %@", p1.clientID];
}

- (void)onDisconnect:(CentrifugeClient *)p0 p1:(CentrifugeDisconnectContext *)p1 {
    _label.text = [NSString stringWithFormat:@"Disconnected..."];
}

- (void)onMessage:(CentrifugeSub *)p0 p1:(CentrifugeMessage *)p1 {
    _label.text = [NSString stringWithFormat:@"%@, %@", p0.channel, p1.data];
}

- (IBAction)clickedTest:(id)sender {
    NSString *data = @"{\"input\": \"hello1234567\"}";
    NSError *error = nil;
    if (![sub publish:[data dataUsingEncoding:NSUTF8StringEncoding] error:&error]) {
        if (error != nil) {
            _label.text = @"Publish error";
        }
    }
}

```

**Comment by FZambia** [comment]
Do `onConnect` and `onDisconnect` callbacks work in your case?

**Comment by TianDaGe** [comment]
I have just checked, it doesnt' work

**Comment by FZambia** [comment]
I think that most probably the problem is in how you register those callbacks. Of course this can be library problem but it worked for me when using Swift. I need some time to figure out how to properly register callbacks in Objective C

**Comment by FZambia** [comment]
Could you share code where you also registering connect and disconnect callbacks - it can help me

**Comment by TianDaGe** [comment]
Sorry, Above code is full code.

**Comment by FZambia** [comment]
I never programmed in ObjC before but don't you need to write at least sth like this:

```
CentrifugeEventHandler *eventHandler = CentrifugeNewEventHandler();
[eventHandler onConnect:self];
[eventHandler onDisconnect:self];

CentrifugeClient *client = CentrifugeNew(url, creds, eventHandler, CentrifugeDefaultConfig());
```

To register connect and disconnect callbacks to event handler?

**Comment by TianDaGe** [comment]
I think, this is correct for objective-c
```
@interface ViewController ()<CentrifugeEventHandler, ....>
... ... 
[eventHandler setDelegate:self]
... ...
- (void)onConnect:(CentrifugeClient *)p0 p1:(CentrifugeConnectContext *)p1 {
    _label.text = [NSString stringWithFormat:@"Connected %@", p1.clientID];
}

- (void)onDisconnect:(CentrifugeClient *)p0 p1:(CentrifugeDisconnectContext *)p1 {
    _label.text = [NSString stringWithFormat:@"Disconnected..."];
}

```

**Comment by TianDaGe** [comment]
onMessage is also same...
delegate must be registed into object...
CentrifugeSubEventHandler *subEventHandler = CentrifugeNewSubEventHandler();
[subEventHandler setDelegate:self];

**Comment by FZambia** [comment]
Does it work now?

**Comment by TianDaGe** [comment]
no, sir.  there is not delegate in your current project.

**Comment by FZambia** [comment]
Hmm, I am almost sure that the problem here is just to find a way to properly register callbacks, looks like I need to dive a bit into ObjectiveC then to say how to do this using this bindings.

**Comment by TianDaGe** [comment]
Currently onMessage function is calling one time in the first. because there is not delegate to get callback.

**Comment by TianDaGe** [comment]
okay sir. Looking forward to hearing from you soon.

**Comment by TianDaGe** [comment]
Hello, @FZambia
Please check swift ios project on your actual device. There is one below issue.
obj-c project is also same.

`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by FZambia** [comment]
@TianDaGe thanks for pointing - I'll find a way to check it out, I tested on real Android device only yet.

**Comment by FZambia** [comment]
@TianDaGe just tried ObjectiveC in emulator - everything works, here is a code:

```objective-c
//
//  ViewController.m
//  CentrifugoObjectiveC
//
//  Created by Alexander Emelin on 05/04/2017.
//  Copyright © 2017 Alexander Emelin. All rights reserved.
//
#import "Centrifuge/Centrifuge.objc.h"
#import "ViewController.h"

@interface ViewController () <CentrifugeConnectHandler, CentrifugeDisconnectHandler, CentrifugeMessageHandler>

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    
    CentrifugeCredentials *creds = CentrifugeNewCredentials(@"42", @"1488055494", @"", @"24d0aa4d7c679e45e151d268044723d07211c6a9465d0e35ee35303d13c5eeff");
    NSString *url = @"ws://localhost:8000/connection/websocket";
    
    CentrifugeEventHandler *eventHandler = CentrifugeNewEventHandler();
    [eventHandler onConnect:self];
    [eventHandler onDisconnect:self];
    CentrifugeClient *client = CentrifugeNew(url, creds, eventHandler, CentrifugeDefaultConfig());
    NSError *error = nil;
    if (![client connect:&error]) {
        if (error != nil) {
            NSLog(@"Error connect");
        }
    }
    
    CentrifugeSubEventHandler *subEventHandler = CentrifugeNewSubEventHandler();
    [subEventHandler onMessage:self];

    error = nil;
    [client subscribe:@"public:chat" events:subEventHandler error:&error];
    if (error != nil) {
        NSLog(@"Subscribe error");
    }
}


- (void)onMessage:(CentrifugeSub *)p0 p1:(CentrifugeMessage *)p1 {
    NSLog(@"Messsage received");
}

- (void)onConnect:(CentrifugeClient *)p0 p1:(CentrifugeConnectContext *)p1 {
    NSLog(@"Connected");
}

- (void)onDisconnect:(CentrifugeClient *)p0 p1:(CentrifugeDisconnectContext *)p1 {
    NSLog(@"Disconnected");
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}


@end

```

I launched app, then sent several messages into channel `public:chat`, then stopped Centrifugo. Here is an output in console:

```
2017-04-06 00:17:52.087 CentrifugoObjectiveC[29854:2009993] Connected
2017-04-06 00:18:08.551 CentrifugoObjectiveC[29854:2010049] Messsage received
2017-04-06 00:18:13.805 CentrifugoObjectiveC[29854:2010043] Messsage received
2017-04-06 00:18:14.304 CentrifugoObjectiveC[29854:2010049] Messsage received
2017-04-06 00:18:14.750 CentrifugoObjectiveC[29854:2010043] Messsage received
2017-04-06 00:18:21.970 CentrifugoObjectiveC[29854:2010055] Messsage received
2017-04-06 00:18:25.941 CentrifugoObjectiveC[29854:2010043] Messsage received
2017-04-06 00:20:40.881 CentrifugoObjectiveC[29854:2010043] Disconnected
```

I have no idea why it have not worked for you - maybe wrong header file? Here is screenshot to show you project structure (XCode Version 8.2.1):

<img width="1141" alt="screen shot 2017-04-06 at 00 23 00" src="https://cloud.githubusercontent.com/assets/1196565/24727617/4ec38790-1a5f-11e7-94d8-91b7c8b183f7.png">

I have not tested on real device yet, will write as soon as I do this.

**Comment by FZambia** [comment]
Successfully installed on real device (iPhone 5c), but I had to disable bitcode in project options:
<img width="1138" alt="screen shot 2017-04-06 at 01 42 35" src="https://cloud.githubusercontent.com/assets/1196565/24730137/8196e59e-1a6a-11e7-8298-cf41f44bcd3c.png">
because I came across a similar issue described here https://github.com/golang/go/issues/16966

Actually there is a traceback in XCode (click on red exclamation mark after failed build) with more information about `clang` exception you got - hopefully it's the same.

**Comment by TianDaGe** [comment]
Hello @FZambia 
You are really awesome. then did you update go-mobile source?
I have just checked. onConnect and publish is working fine.
But onMessage and onDisconnect is not working.
And project is built on real device. I copied and pasted your full source. but not working.
If you updated go-mobile source, please let me know?
Thanks

**Comment by TianDaGe** [comment]
And I stopped centrifugo and relauch app project. then get onDisconnect event.
So it seems app is getting a event only one time in the first. why?

**Comment by TianDaGe** [comment]
You really awesome! Thanks. 
Real device is working fine, I think my XCode has some issues.

**Comment by TianDaGe** [comment]
Hello @FZambia 
I got why the project is not working on simulator well.
Did you get result on simulator or real device? I checked objective-c and swift project.
If I include centrifuge.framework and run CentrifugeNewCredentials(), the simulator is crashing app with below error.
`Message from debugger: The LLDB RPC server has crashed. The crash log is located in ~/Library/Logs/DiagnosticReports and has a prefix 'lldb-rpc-server'. Please file a bug and attach the most recent crash log.`
I have found about this error, but I can't get reason. perhaps is there one problem in the project?
Anyway, real device is working fine.
My XCode version is 8.3.

**Comment by FZambia** [comment]
At moment I've checked both simulator and real devices - both working fine for me. I will update my XCode to 8.3 and try again.

**Comment by joeblew99** [comment]
@FZambia you have a 100% golang stack on server and mobile, so you can use golang quic instead of web sockets. Worth thinking from a code maintenance and perf aspect.
QUIC is really easy to use and is not kernel dependent and runs on mobile networks MUCH bette than websockets. The telecom provides run everything using UPD (whihc is the transport QUIC ride on).

See this for just how easy it can be !
https://github.com/simia-tech/netx/blob/master/PRESENTATION.slide

**Comment by FZambia** [comment]
@joeblew99 thanks, I already thought about QUIC, maybe one day it will be in Centrifugo. We have little use on mobile at moment, so as soon as developers will integrate Centrifugo into mobile stack we can consider improvements in this area. Do you have experience with QUIC in mobile networks btw or maybe sth to read about this?

It's still important to have Websocket as stable and supported by browsers and native mobile language libraries transport.

**Comment by TianDaGe** [comment]
Hello @FZambia 
How is it running on XCode 8.3?

**Comment by FZambia** [comment]
@TianDaGe already installed it but had no time to check - will do this later today

**Comment by FZambia** [comment]
@TianDaGe the same code I posted above works on iPhone 5c installed via XCode 8.3 too

**Comment by TianDaGe** [comment]
Thanks for your reply, I will check on my side again.

**Comment by FZambia** [comment]
@TianDaGe any news, did you make it work for you?

**Comment by TianDaGe** [comment]
no, @FZambia.
Simulator debugging is crashed when app is started, but simulator works, not crash.
So I am developing with actual device.

**Comment by FZambia** [comment]
Just updated Android and iOS examples to use latest bindings so we are done for a moment.

@TianDaGe that crash is strange, the error states for looking at crash log and filing a bug in XCode - maybe this is what you should do.
