### ISSUE TITLE
Can you add create token feature into the project.

### ISSUE THREAD

**Issue by TianDaGe** [centrifugal/centrifuge-mobile#5]
Hello @FZambia 
Now centirfuge-mobile is great. but developers have to create token in every platform.
I think, if you add create token feature into the centifuge-mobile, it will more better than now,
Regards

**Comment by FZambia** [comment]
Hi, I have not added token generation function to this client to emphasize  idiomatic Centrifugo usage - when token should be generated on app backend without showing secret key to client. What is your use case - do you have application backend?

**Comment by TianDaGe** [comment]
Yes, I have webservice backend and mobile app. And I am using centrifugo for websocket service. I created token generation function on mobile app side manually. but I thought if token generation function is in the centrifuge.framework, it would be better.
```
timestamp = CentrifugeTimestamp();
token = CentrifugeNewAuthToken(secret, id, timestamp, info)
```

**Comment by TianDaGe** [comment]
One more, I will share my auth token generation function of obj-c
I looked swift code, it is very simple but my obj-c code looks dirty... :(
```
#import <CommonCrypto/CommonDigest.h>
#import <CommonCrypto/CommonHMAC.h>

NSString *timestamp = CentrifugeTimestamp();
NSString *token =[self createToken:[NSString stringWithFormat:@"%@%@%@",user, timestamp, @""] secret:@"secret"];

- (NSString *)createToken:(NSString *)data secret:(NSString *)key {
    NSData *cdata = [data dataUsingEncoding:NSASCIIStringEncoding];
    NSData *ckey = [key dataUsingEncoding:NSASCIIStringEncoding];
    unsigned char cHMAC[CC_SHA256_DIGEST_LENGTH];
    
    CCHmac(kCCHmacAlgSHA256, ckey.bytes, (CC_LONG)ckey.length, cdata.bytes, (CC_LONG)cdata.length, cHMAC);
    NSData *HMACData = [[NSData alloc] initWithBytes:cHMAC length:sizeof(cHMAC)];
    
    const unsigned char *buffer = (const unsigned char *)[HMACData bytes];
    NSString *HMAC = [NSMutableString stringWithCapacity:HMACData.length * 2];
    
    for (int i = 0; i < HMACData.length; ++i)
        HMAC = [HMAC stringByAppendingFormat:@"%02lx", (unsigned long)buffer[i]];
    
    return HMAC;
}
```

**Comment by FZambia** [comment]
But do you aware of the fact that you sharing secret key with your clients? This is not secure - the only two who must know secret is Centrifugo and your service backend. So in idiomatic case your app should ask your backend for token - otherwise any user can connect to Centrifugo as another user

**Comment by TianDaGe** [comment]
Thanks your advice.
So I will need secret key from backend,

**Comment by FZambia** [comment]
Not a secret, all credentials - user, timestamp, info and token based on user, timestamp, info and secret key. Secret key should never be in client side code.
