### ISSUE TITLE
Can you make multi credentials example?

### ISSUE THREAD

**Issue by TianDaGe** [centrifugal/centrifuge-mobile#6]
Hi,
I made one simulator to test centrifugo server's performance.
but if I create about 4 credentials and publish the data asynchronously and continuously, the go application is stopped after some mins.
I think, I may wrong. So I request multi-credentials expample in one go applicaton to you.
Regards,

**Comment by TianDaGe** [comment]
One, more
I implemented centrifuge.aar with android studio 3. it was working fine android studio 2.3, but i was not working fine as your method. As you know, android studio 3 is published recently.
I looked your posted article about the go-mobile centrifugo application.
I fixed it on android studio 3.
-----------------------------------------
1. copy centrifuge.aar to "libs" directory of the android source proejct.
2. add following lines in build.gradle

android {
... ...
     repositories {
        flatDir {
            dirs 'libs'
        }
    }
}

dependencies {
... ...
    compile(name:'centrifuge', ext:'aar')
}

**Comment by FZambia** [comment]
Hi, thanks for an info! 

What do you mean under multi credentials? [Here](https://github.com/centrifugal/centrifuge-mobile/blob/master/examples/go/throughput.go) is an example that generates many connections. What exactly you are trying to achieve? Maybe you can post your code here.

**Comment by TianDaGe** [comment]
hi, thanks your advice.
I am trying to achieve the example that several clients will publish different messages concurrency with themselves channels continuously until get stop-command.
