### ISSUE TITLE
get `permission denied` even publish is true

### ISSUE THREAD

**Issue by williambao** [centrifugal/centrifuge-mobile#7]
Hi,
In Android, When I publish data directly, It throw exception like below pic.
<img width="1144" alt="test" src="https://user-images.githubusercontent.com/779521/27339834-7340f002-560b-11e7-8ca6-eae0f4a94db6.png">
But I already set the `publish` to `true` in config.

**Comment by FZambia** [comment]
Hello, have you set `"publish": true` for namespace `messages`?

**Comment by williambao** [comment]
@FZambia Yes, When the first time I connect the channel, and call `publish` function is ok. 
When I publish  data finished, I called `channel.unsubscribe()`.
If reconnect to channel and call `publish`, It return `permission denied`.

**Comment by FZambia** [comment]
Ah, I am a bit confused now - you closed an issue because issue now solved or what reason? 😕
